Update patch set 1
Patch Set 1:

ml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Warning: org.ejml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Warning: org.ejml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Warning: org.ejml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Warning: org.ejml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Warning: org.ejml.ops.MatrixVisualization: can't find referenced class javax.swing.JFrame
Reading library jar [/home/jenkins/android/workspace/android/jellybean/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes.jar]
Reading library jar [/home/jenkins/android/workspace/android/jellybean/out/target/common/obj/JAVA_LIBRARIES/android_stubs_current_intermediates/classes.jar]
Reading library jar [/home/jenkins/android/workspace/android/jellybean/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jar]
Warning: org.ejml.ops.MatrixComponent: can't find referenced class javax.swing.JPanel
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.Dimension
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.Dimension
Warning: org.ejml.ops.MatrixComponent: can't find referenced method 'void setPreferredSize(java.awt.Dimension)' in class org.ejml.ops.MatrixComponent
Warning: org.ejml.ops.MatrixComponent: can't find referenced method 'void setMinimumSize(java.awt.Dimension)' in class org.ejml.ops.MatrixComponent
Warning: org.ejml.ops.MatrixComponent: can't find referenced method 'void repaint()' in class org.ejml.ops.MatrixComponent
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.Graphics
Warning: org.ejml.ops.MatrixComponent: can't find referenced class javax.swing.JPanel
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.Graphics
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.image.BufferedImage
Warning: org.ejml.ops.MatrixComponent: can't find referenced class java.awt.Graphics

Warning: there were 22 unresolved references to classes or interfaces.
         You may need to specify additional library jars (using '-libraryjars'),
         or perhaps the '-dontskipnonpubliclibraryclasses' option.
Warning: there were 3 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile them and try again.
         Alternatively, you may have to specify the options 
         '-dontskipnonpubliclibraryclasses' and/or
         '-dontskipnonpubliclibraryclassmembers'.
Error: Please correct the above warnings first.

Patch-set: 1